### ISSUE TITLE
Unauthorized Domain 

### ISSUE THREAD

**Issue by Villanuevand** [how-to-firebase/firelist-react#2]
Trying to loggin in `https://react.fullstackfirebase.com/`  throw me an error: 

<img width="1679" alt="captura de pantalla 2018-07-17 a la s 10 05 42" src="https://user-images.githubusercontent.com/1209238/42819165-249a7d06-89a9-11e8-8bd8-caaf49653684.png">

Check this => https://stackoverflow.com/questions/37344066/firebase-this-domain-is-not-authorized/48475438#48475438

**Comment by deltaepsilon** [comment]
Thanks for the heads up @Villanuevand 

I have it fixed!
